---
# Source: azure-secretprovider/templates/secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secretprovider-certificate
spec:
  provider: azure
  parameters:
    keyvaultName: 
    objects: |
      array:
        - |
          objectName: getshifting-tls-cert
          objectType: secret
        - |
          objectName: getshifting-tls-key
          objectType: secret
    tenantId: 
    usePodIdentity: "false"
    clientID: 
  secretObjects:
    - data:
      - key: tls.crt
        objectName: getshifting-tls-cert
      - key: tls.key
        objectName: getshifting-tls-key
      secretName: getshifting-tls
      type: kubernetes.io/tls

