# Source: azure-secretprovider/templates/secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secretprovider
spec:
  provider: azure
  parameters:
    keyvaultName: kv-euw-shift
    objects: |
      array:
        - |
          objectName: Grafana-AdminPassword
          objectType: secret
        - |
          objectName: Grafana-AdminUsername
          objectType: secret
        - |
          objectName: Grafana-SlackWebHook
          objectType: secret
    tenantId: 7e4an71d-a123-a123-a123-abcd12345678
    usePodIdentity: "false"
    clientID: acc78f4a-932a-415f-a77e-e7e1071a0161
  secretObjects:
    - data:
      - key: admin-password
        objectName: Grafana-AdminPassword
      - key: admin-user
        objectName: Grafana-AdminUsername
      secretName: grafana-admin
      type: Opaque
    - data:
      - key: SLACKWEBHOOK
        objectName: Grafana-SlackWebHook
      secretName: grafana-slackwebhook
      type: Opaque
