tenantId: 7e4an71d-a123-a123-a123-abcd12345678
clientID: acc78f4a-932a-415f-a77e-e7e1071a0161
keyvaultName: kv-euw-shift
secrets:
  - Grafana-AdminPassword
  - Grafana-AdminUsername
  - Grafana-SlackWebHook
secretObjects:
  - secretName: grafana-admin
    data:
      - key: admin-password
        objectName: Grafana-AdminPassword
      - key: admin-user
        objectName: Grafana-AdminUsername
    type: Opaque
  - secretName: grafana-slackwebhook
    data:
      - key: SLACKWEBHOOK
        objectName: Grafana-SlackWebHook
    type: Opaque
