secrets:
  - getshifting-tls-cert
  - getshifting-tls-key
secretObjects:
  - secretName: getshifting-tls
    data:
      - key: tls.crt
        objectName: getshifting-tls-cert
      - key: tls.key
        objectName: getshifting-tls-key
    type: kubernetes.io/tls
