{
 "title": "Vertex AKS Resources",
 "tags": [
  "azure",
  "pods",
  "cluster",
  "memory",
  "cpu",
  "status",
  "vtxops",
  "Vertex"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vertex AKS Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__range])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}) * 100",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) * 100",
     "legendFormat": "Memory(%)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - min(kube_pod_start_time{namespace=\"$namespace\"})) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;  margin-top: 1px;\">\n  <h1><span style=\"color: Cyan; font-weight: bold;\">VTX ${namespace}</span></h1>\n</div>\n"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 2, "x": 21, "y": 1 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 1, "x": 23, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, status) (kube_pod_status_phase{namespace=\"$namespace\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$__range])) > 0)"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "table",
   "gridPos": { "h": 25, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 25, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"} * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=~\"cpu\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "description": "PVCs in Pending State",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Jobs Activated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Cont. Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cont. Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs Full in 2 days",
   "type": "stat",
   "description": "PVCs Full in 2 days - Based on Daily Usage",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n  count (\r\n    (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"})\r\n    and\r\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}[1d], 2 * 24 * 60 * 60) < 0)\r\n  )\r\n)\r\nor\r\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "description": "PVCs in Lost State",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "table",
   "gridPos": { "h": 21, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "table",
   "gridPos": { "h": 21, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Cont Restarts < 30min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[30m]))"
    }
   ]
  },
  {
   "title": "Cont. Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days",
   "type": "stat",
   "description": "PVCs Full in 5 days - Based on Daily Usage",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n  count (\r\n    (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"})\r\n    and\r\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}[1d], 5 * 24 * 60 * 60) < 0)\r\n  )\r\n)\r\nor\r\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week",
   "type": "stat",
   "description": "PVCs Full in 1 Week - Based on Daily Usage",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n  count (\r\n    (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"})\r\n    and\r\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\r\n  )\r\n)\r\nor\r\nvector(0)"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VTX CPU Usage/Request/Limits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", cluster=\"$cluster\"})",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "VTX Memory Usage/Request/Limits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\r\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\r\n)",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 } },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarted pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[$__range]) > 0",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Pending\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarting pods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1m]) > 0",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Failed/Unknown pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Unknown|Failed\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running pods",
     "type": "table",
     "gridPos": { "h": 24, "w": 10, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Succeeded|Running\"} == 1",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "kube_pod_status_phase{namespace=\"vtxops\", phase=~\"Succeeded|Running\"} == 1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 10, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 11, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Pending\"}[1m]) > 0",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, container) (container_memory_working_set_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    { "type": "alertlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 139 } },
    {
     "title": "Pending pods",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "changes(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Pending\"}[1m]) > 0",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    },
    {
     "title": "Memory difference (Limits - Usage)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}) - sum by(pod, container) (container_memory_working_set_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\".+\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (pod, container) /\r\nsum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\".+\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (pod, container) ",
       "legendFormat": "{{pod}} {{container}}"
      }
     ]
    },
    {
     "title": "Memory usage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "CPU usage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "sum by(namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}