# Default values for aks-permissions.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ClusterRoleBindings - for cluster-wide permissions
clusterRoleBindings: []

# RoleBindings - for namespace-specific permissions
roleBindings: []
